"""
chest_definitions.py
--------------------
Static definitions for all chest types, their display names, colors,
pattern detection signatures, and default item lists.

This file is bundled with the app and updated via app updates.
Users do not need to edit this file.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Chest type definitions: (chest_name, display_name, hex_color)
# ---------------------------------------------------------------------------

CHEST_DEFINITIONS: list[tuple[str, str, str]] = [
    ("Razador's Chest", "Razador", "#c0392b"),
    ("Nemere's Chest", "Nemere", "#aed6f1"),
    ("Jotun Thrym's Chest", "Jotun Thrym", "#a9dfbf"),
    ("Hellgates Chest", "Blue Death", "#1a1a1a"),
    ("Chest of the Owl King", "Natuhu", "#D6D192"),
    ("Taliko's Riches", "Taliko", "#9b59b6"),
    ("Monkey God's Treasure", "Hells Nightmare", "#e67e22"),
    ("Nalantir's Legacy", "Nalantir", "#1abc9c"),
    ("Treasure of Thorns", "Nozdormu", "#27ae60"),
    ("Chest of Platun", "Platun", "#7f8c8d"),
    ("Heroic Chest of Razadere", "Razador (Heroic)", "#922b21"),
    ("Heroic Chest of Nemedere", "Nemere (Heroic)", "#5dade2"),
    ("Heroic Chest of Jatuno", "Jotun Thrym (Heroic)", "#52be80"),
    ("World Bounty Chest (Normal)", "Bounty (Normal)", "#f39c12"),
]

# ---------------------------------------------------------------------------
# Pattern chests: detected by loot signature, not log text
# (chest_name, [required_items_lowercase])
# ---------------------------------------------------------------------------

PATTERN_CHEST_DEFINITIONS: list[tuple[str, list[str]]] = [
    ("World Bounty Chest (Normal)", ["Monstrous Feather", "Monstrous Claw", "Shard"]),
]

# ---------------------------------------------------------------------------
# Default item lists per chest type
# Items have a default price of 0 unless the user sets one in prices_config.txt
# ---------------------------------------------------------------------------

DEFAULT_ITEMS: dict[str, list[str]] = {
    "Razador's Chest": [
        "Shard",
        "Energy Fragment",
        "Bewitch Item",
        "Bless Item",
        "Magic Stone",
        "Yellow Belt",
        "Brown Belt",
        "Black Yarn",
        "Thief's Gloves",
        "Fragment of a Pass [U-1]",
        "Horn of Razador",
        "Leather Belt+0",
        "Experience Ring",
        "Charred Pass",
        "Green Pearl",
        "Flame Stone",
        "Orange Yarn",
        "Purple Potion(L)",
        "Lucky Gold Coin",
        "Skill Book Chest [M-G]",
        "Fragment of a Pass [U-2]",
        "Magma Ring",
        "Black Pearl",
        "Lava Spirit Stone",
        "Pearl Dust",
        "Flaming Mane",
        "White Pearl",
        "Blue Pearl",
        "Blood-Red Pearl",
        "Demon's Keepsake",
        "Ornamental Hairpin",
        "Piece of Fabric",
        "Fishbones",
        "Fragment of a Pass [R-1]",
        "Yeti Fur",
        "Firepotion",
        "Leaf",
        "Piece of Stone",
        "Broken Porcelain",
        "Piece of Broken Armor",
        "Combo-Ball",
        "Casket of Spirit Stones",
        "Soul Stone+",
        "Green Potion(L)",
        "Piece of Gem",
        "Blessing Scroll",
        "Potion of Haste",
        "Rusty Blade",
        "Fragment of a Pass [R-2]",
        "Golden Hook",
        "Iron",
        "Mithril",
        "Etherplasma",
    ],
    "Nemere's Chest": [
        "Shard",
        "Energy Fragment",
        "Bewitch Item",
        "Bless Item",
        "Magic Stone",
        "Yellow Belt",
        "Brown Belt",
        "Orange Yarn",
        "Black Yarn",
        "Purple Potion(L)",
        "Experience Ring",
        "Lucky Gold Coin",
        "Thief's Gloves",
        "Yellow Pearl",
        "Frostfire Stone",
        "Ice-cold Pass",
        "Fragment of a Pass [U-1]",
        "Fragment of a Pass [U-2]",
        "Horn of Nemere",
        "Magic Iceblock",
        "Structure of Ice",
        "Holy Stone",
        "Gold Buckle",
        "Pearl Dust",
        "Demon's Ashes",
        "Mithril",
        "Lava Spirit Stone",
        "Leather Belt+0",
        "Skill Book Chest [M-G]",
        "Black Pearl",
        "White Pearl",
        "Blue Pearl",
        "Blood-Red Pearl",
        "Yeti Fur",
        "Broken Porcelain",
        "Rusty Blade",
        "Combo-Ball",
        "Fishbones",
        "Piece of Stone",
        "Casket of Spirit Stones",
        "Soul Stone+",
        "Blessing Scroll",
        "Potion of Haste",
        "Green Potion(L)",
        "Demon's Gem",
        "Demon's Keepsake",
        "Kaki Blossom",
        "Ornamental Hairpin",
        "Fragment of a Pass [N-1]",
        "Fragment of a Pass [N-2]",
        "Flaming Mane",
    ],
    "Jotun Thrym's Chest": [
        "Shard",
        "Energy Fragment",
        "Bewitch Item",
        "Bless Item",
        "Magic Stone",
        "Yellow Belt",
        "Brown Belt",
        "Orange Yarn",
        "Black Yarn",
        "Grass-covered Pass",
        "Demon's Ashes",
        "Mithril",
        "Stone of the Dryads",
        "Heaven and Hell",
        "Hallowed Tree Gum",
        "Zelkoven-Branch",
        "Magical Dice",
        "Lava Spirit Stone",
        "Ring Element",
        "Leather Belt+0",
        "Purple Potion(L)",
        "Experience Ring",
        "Lucky Gold Coin",
        "Thief's Gloves",
        "Legendary Diary",
        "Skill Book Chest [M-G]",
        "Violett Pearl",
        "Black Pearl",
        "Fragment of a Pass [U-1]",
        "Fragment of a Pass [U-2]",
        "White Pearl",
        "Blue Pearl",
        "Blood-Red Pearl",
        "Leaf",
        "Piece of Gem",
        "Piece of Broken Armor",
        "Demon's Gem",
        "Demon's Keepsake",
        "Fishbones",
        "Piece of Stone",
        "Kaki Blossom",
        "Ornamental Hairpin",
        "Casket of Spirit Stones",
        "Soul Stone+",
        "Flaming Mane",
        "Blessing Scroll",
        "Potion of Haste",
        "Green Potion(L)",
        "Fragment of a Pass [J-1]",
        "Fragment of a Pass [J-2]",
    ],
    "Hellgates Chest": [
        "Shard",
        "Energy Fragment",
        "Inner Light",
        "Soulstone of Undeads",
        "Agate",
        "Bewitched Ashes",
        "Black Dye",
        "Emblem Piece",
        "Emblem Chest",
        "Companion Serum [50-250]",
        "Dexterity of the Smith (Chest)",
        "Page",
        "Skill Book Chest [M-G]",
        "Sky-Blue Pearl",
        "Black Pearl",
        "Yellow Belt",
        "Brown Belt",
        "Orange Yarn",
        "Black Yarn",
        "Fragment of a Pass [U-2]",
        "Fragment of a Pass [U-1]",
        "White Pearl",
        "Blue Pearl",
        "Blood-Red Pearl",
        "Leaf",
        "Piece of Gem",
        "Piece of Broken Armor",
        "Flaming Mane",
        "Demon's Keepsake",
        "Ornamental Hairpin",
        "Yeti Fur",
        "Broken Porcelain",
        "Rusty Blade",
        "Piece of Fabric",
        "Fishbones",
        "Piece of Stone",
        "Casket of Spirit Stones",
        "Soul Stone+",
        "Blessing Scroll",
        "Potion of Haste",
        "Green Potion(L)",
        "Fragment of a Pass [R-1]",
        "Combo-Ball",
        "Fragment of a Pass [R-2]",
        "Demon's Gem",
        "Kaki Blossom",
        "Fragment of a Pass [N-1]",
        "Fragment of a Pass [N-2]",
        "Fragment of a Pass [J-2]",
        "Fragment of a Pass [J-1]",
    ],
    "Chest of the Owl King": [
        "Shard",
        "Storm Crystal Shard",
        "Green Owlbile",
        "Red Owlbile",
        "Blue Owlbile",
        "Green Owl Totem",
        "Bright rough Diamond",
        "Red Kalant",
        "Green Tasman",
        "Violett Tasman",
        "Blue Tasman",
        "Green Meteor",
        "Red Meteor",
        "Piece of an Owl Pass [L]",
        "Piece of an Owl Pass [R]",
        "Natuhu's Heart",
        "Suran's Pauldron",
        "Companion Serum [50-250]",
        "Skill Book Chest [M-G]",
        "Yellow Belt",
        "Brown Belt",
        "Orange Yarn",
        "Black Yarn",
        "Emblem Chest",
    ],
    "World Bounty Chest (Normal)": [
        "Shard",
        "Storm Crystal Shard",
        "Spirit Emblem Chest",
        "Aura Emblem Chest",
        "Magical Smithing Hammer",
        "Nataraja's Medallion",
        "Midnight Potion",
        "Hammer of Althor",
        "Althor's Cosmic Dust",
        "Book of Truth",
        "Bloodred Flower",
        "Monstrous Feather",
        "Monstrous Claw",
        "Magical Dice",
        "Holy Stone",
        "Etherplasma",
        "Emblem Piece",
        "Emblem Chest",
        "Skill Book Chest [M-G]",
        "Companion Serum [50-250]",
        "Yellow Belt",
        "Brown Belt",
        "Orange Yarn",
        "Black Yarn",
        "Ice-cold Pass",
        "Charred Pass",
        "Grass-covered Pass",
        "Hellish Pass",
        "Verdammter Runenstein",
    ],
    "Chest of Platun": [
        "Shard",
        "Storm Crystal Shard",
        "Gray Fragment",
        "White Fragment",
        "Yellow Fragment",
        "Purple Fragment",
        "Gray Shiny Fragment",
        "Green Shiny Fragment",
        "Yellow Shiny Fragment",
        "Red Shiny Fragment",
        "Blue Shiny Fragment",
        "Violett Shiny Fragment",
        "Awesome Power of the Sigil-smith",
        "Eye of the Sigil-smith",
        "Awesome Power of the Sigil-smith (6/7)",
        "Awesome Power of the Sigil-smith (8)",
        "Eye of the Sigil-smith (6/7)",
        "Eye of the Sigil-smith (8)",
        "Sigil Experience Crystal I",
        "Sigil Experience Crystal II",
        "Divine Orb",
        "Greater Divine Orb",
        "Annulment Orb",
        "Exalted Orb",
        "Greater Exalted Orb",
        "Chaos Orb",
        "Greater Chaos Orb",
        "Magical Dice",
        "Holy Stone",
        "Etherplasma",
        "Emblem Piece",
        "Midnight Ore",
        "Midnight Dust",
        "Liquid Night",
        "Midnight Vessel",
        "Nataraja's Medallion",
        "Midnight Potion",
    ],
    "Taliko's Riches": [
        "Shard",
        "Storm Crystal Shard",
        "Energy Fragment",
        "Yellow Citrindust",
        "Blue Citrindust",
        "Red Citrine Dust",
        "Yellow Citrine",
        "Polished yellow Citrin",
        "Polished blue Citrin",
        "Red Citrin",
        "Polished red Citrin",
        "Red Meteor splinter",
        "Blue Meteor splinter",
        "Green Meteor splinter",
        "Talikos Jewel",
        "Talikos Magical Fire",
        "Midnight Ore",
        "Midnight Dust",
        "Liquid Night",
        "Midnight Vessel",
        "Shard of a Legendary Soul Stone [1]",
        "Fantastic Blessing",
        "Companion Serum [50-250]",
        "Skill Book Chest [M-G]",
        "Large Portal Stone (Level 1)",
    ],
    "Monkey God's Treasure": [
        "Shard",
        "Storm Crystal Shard",
        "Energy Fragment",
        "Nataraja's Medallion",
        "Midnight Potion",
        "Dragonfire Stone",
        "Dragonfire Crystal",
        "Dragonfire Shard",
        "Companion Enchantment",
        "Companion Bewitchment",
        "Companion Serum [250-500]",
        "Magical Dice",
        "Holy Stone",
        "Etherplasma",
        "Emblem Piece",
        "Fabled Blessing",
        "Shard of a Legendary Soul Stone [2]",
        "Blue Belt",
        "Gray Belt",
        "Adanos's Stone",
        "Companion Serum [50-250]",
        "Skill Book Chest [M-G]",
        "Artifact of the Undead",
        "Midnight Ore",
        "Midnight Dust",
        "Liquid Night",
        "Midnight Vessel",
    ],
    "Nalantir's Legacy": [
        "Shard",
        "Storm Crystal Shard",
        "Energy Fragment",
        "Nataraja's Medallion",
        "Magical Dice",
        "Holy Stone",
        "Etherplasma",
        "Emblem Piece",
        "Shard of a Legendary Soul Stone [3]",
        "Adanos's Powerful Stone",
        "Violet Belt",
        "Green Belt",
        "Midnight Ore",
        "Midnight Dust",
        "Liquid Night",
        "Midnight Vessel",
        "Nalantir's Scale",
        "Nalantir's Heart",
        "Iron Shell",
        "Shimmering White Pearl",
        "Shimmering Blue Pearl",
        "Shimmering Red Pearl",
        "Nalantir's Trophy",
        "Companion Serum [50-250]",
        "Companion Serum [250-500]",
        "Companion Serum [500-750]",
        "Midnight Potion",
        "Skill Book Chest [M-G]",
        "Skill Book Chest [G-P]",
        "Gray Fragment",
        "White Fragment",
        "Green Fragment",
        "Yellow Fragment",
        "Blue Fragment",
        "Purple Fragment",
        "Red Fragment",
    ],
    "Treasure of Thorns": [
        "Shard",
        "Storm Crystal Shard",
        "Energy Fragment",
        "Nataraja's Medallion",
        "Magical Dice",
        "Holy Stone",
        "Etherplasma",
        "Emblem Piece",
        "Shard of a Legendary Soul Stone [4]",
        "Adanos's Legendary Stone",
        "Blue Belt",
        "Gray Belt",
        "Violet Belt",
        "Green Belt",
        "Midnight Ore",
        "Midnight Dust",
        "Liquid Night",
        "Midnight Vessel",
        "Amulet of the Wilderness +0",
        "Amulet of the Fortress +0",
        "Amulet of the Berserker +0",
        "Amulet of Atoning Fire +0",
        "Lava Jewel",
        "Ice Jewel",
        "Shadow Shard",
        "Shadow Jewel",
        "Companion Serum [50-250]",
        "Companion Serum [250-500]",
        "Companion Serum [500-750]",
        "Skill Book Chest [M-G]",
        "Skill Book Chest [G-P]",
        "Rainbow Pearl",
        "Devilish Blessing",
        "Devilish Enchanting",
        "Green Prismal",
        "Midnight Potion",
        "Gray Fragment",
        "White Fragment",
        "Green Fragment",
        "Yellow Fragment",
        "Blue Fragment",
        "Purple Fragment",
        "Red Fragment",
    ],
    "Heroic Chest of Razadere": [
        "Shard",
        "Energy Fragment",
        "Gray Fragment",
        "White Fragment",
        "Yellow Fragment",
        "Purple Fragment",
        "Red Fragment",
        "Bewitch Item",
        "Bless Item",
        "Magic Stone",
        "Flame Stone",
        "Yellow Belt",
        "Brown Belt",
        "Orange Yarn",
        "Black Yarn",
        "Black Pearl",
        "Green Pearl",
        "Charred Pass",
        "Lava Spirit Stone",
        "Fragment of a Pass [U-1]",
        "Fragment of a Pass [U-2]",
        "Horn of Razador",
        "Magma Ring",
        "Firepotion",
        "Etherplasma",
        "Leather Belt+0",
        "Pearl Dust",
        "Iron",
        "Mithril",
        "Golden Hook",
        "Purple Potion(L)",
        "Experience Ring",
        "Lucky Gold Coin",
        "Thief's Gloves",
        "Skill Book Chest [M-G]",
        "White Pearl",
        "Blue Pearl",
        "Blood-Red Pearl",
        "Flaming Mane",
        "Demon's Keepsake",
        "Ornamental Hairpin",
        "Piece of Fabric",
        "Leaf",
        "Fishbones",
        "Piece of Stone",
        "Piece of Broken Armor",
        "Piece of Gem",
        "Casket of Spirit Stones",
        "Soul Stone+",
        "Blessing Scroll",
        "Potion of Haste",
        "Green Potion(L)",
        "Fragment of a Pass [R-1]",
        "Combo-Ball",
        "Yeti Fur",
        "Broken Porcelain",
        "Rusty Blade",
        "Fragment of a Pass [R-2]",
    ],
    "Heroic Chest of Nemedere": [
        "Shard",
        "Energy Fragment",
        "Gray Fragment",
        "White Fragment",
        "Yellow Fragment",
        "Purple Fragment",
        "Blue Fragment",
        "Bewitch Item",
        "Bless Item",
        "Magic Stone",
        "Frostfire Stone",
        "Yellow Belt",
        "Brown Belt",
        "Orange Yarn",
        "Black Yarn",
        "Yellow Pearl",
        "Ice-cold Pass",
        "Lava Spirit Stone",
        "Fragment of a Pass [U-1]",
        "Fragment of a Pass [U-2]",
        "Horn of Nemere",
        "Magic Iceblock",
        "Structure of Ice",
        "Holy Stone",
        "Leather Belt+0",
        "Pearl Dust",
        "Demon's Ashes",
        "Mithril",
        "Gold Buckle",
        "Purple Potion(L)",
        "Experience Ring",
        "Lucky Gold Coin",
        "Thief's Gloves",
        "Skill Book Chest [M-G]",
        "Black Pearl",
        "White Pearl",
        "Blue Pearl",
        "Blood-Red Pearl",
        "Yeti Fur",
        "Broken Porcelain",
        "Rusty Blade",
        "Combo-Ball",
        "Fishbones",
        "Piece of Stone",
        "Casket of Spirit Stones",
        "Soul Stone+",
        "Blessing Scroll",
        "Potion of Haste",
        "Green Potion(L)",
        "Fragment of a Pass [N-1]",
        "Fragment of a Pass [N-2]",
        "Demon's Gem",
        "Demon's Keepsake",
        "Kaki Blossom",
        "Ornamental Hairpin",
        "Flaming Mane",
    ],
    "Heroic Chest of Jatuno": [
        "Shard",
        "Energy Fragment",
        "Gray Fragment",
        "White Fragment",
        "Yellow Fragment",
        "Purple Fragment",
        "Green Fragment",
        "Bewitch Item",
        "Bless Item",
        "Magic Stone",
        "Yellow Belt",
        "Brown Belt",
        "Orange Yarn",
        "Black Yarn",
        "Grass-covered Pass",
        "Demon's Ashes",
        "Mithril",
        "Stone of the Dryads",
        "Heaven and Hell",
        "Hallowed Tree Gum",
        "Zelkoven-Branch",
        "Magical Dice",
        "Lava Spirit Stone",
        "Ring Element",
        "Leather Belt+0",
        "Purple Potion(L)",
        "Experience Ring",
        "Lucky Gold Coin",
        "Thief's Gloves",
        "Legendary Diary",
        "Skill Book Chest [M-G]",
        "Violett Pearl",
        "Black Pearl",
        "Fragment of a Pass [U-1]",
        "Fragment of a Pass [U-2]",
        "White Pearl",
        "Blue Pearl",
        "Blood-Red Pearl",
        "Leaf",
        "Piece of Gem",
        "Piece of Broken Armor",
        "Demon's Gem",
        "Demon's Keepsake",
        "Fishbones",
        "Piece of Stone",
        "Kaki Blossom",
        "Ornamental Hairpin",
        "Casket of Spirit Stones",
        "Soul Stone+",
        "Flaming Mane",
        "Blessing Scroll",
        "Potion of Haste",
        "Green Potion(L)",
        "Fragment of a Pass [J-1]",
        "Fragment of a Pass [J-2]",
    ],
}
