name: Build and Release EXE

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
                  pip install pyinstaller

            - name: Build EXE
              run: |
                  pyinstaller --onefile --noconsole --name "Chest Tracker" main.py

            - name: Zip files
              run: |
                  powershell Compress-Archive -Path dist/*.exe, prices_config.txt -DestinationPath ChestTracker.zip

            - name: Upload to Release
              uses: softprops/action-gh-release@v2
              with:
                  files: ChestTracker.zip
